### ISSUE TITLE
Not able to install the package on Kaggle.

### ISSUE THREAD

**Issue by brbisheng** [fbertran/plsRglm#1]
Dear Professor, 

In the documentary, it is indicated that: "Depends R (>= 2.10)"

However, the installation on Kaggle is unsuccessful with the following information: 
'Error: (converted from warning) package ‘statnet.common’ is not available (for R version 3.4.2)'

Thank you.

Best regards,

Sheng BI

**Comment by fbertran** [comment]
Dear Sheng BI

Thank you for your interest for the plsRglm package.

As you spotted out, the new version of statnet.common (4.2) requires R (≥ 3.5). Yet plsRglm works fine with an older version of this package. To install an older version of statnet.common, let's say 4.0.0, you can use the following code snippet that uses the install_version function of the devtools package that is available on Kaggle. The install an version 2.4 of the sna package and finally plsRglm.

The code to install the package on Kaggle and have an example running is the following:

require(devtools)
install_version("statnet.common", version = "4.0.0", 
repos = "http://cran.us.r-project.org", type="source")
library(statnet.common)
install_version("sna", version = "2.4", repos = "http://cran.us.r-project.org")
library(sna)
install.packages("plsRglm")
library("plsRglm")
data(Cornell)
XCornell<-Cornell[,1:7]
yCornell<-Cornell[,8]

modplsglm <- plsRglm(yCornell,XCornell,10,modele="pls-glm-gaussian")

It is available as a kernel here:
https://www.kaggle.com/fbertran/kernel0ce3b88d58

The first part of the log is the install of the package. You get at the end of the log the output of a plsRglm function.
____************************************************____

Family: gaussian 
Link function: identity 

____Component____ 1 ____
____Component____ 2 ____
____Component____ 3 ____
____Component____ 4 ____
____Component____ 5 ____
____Component____ 6 
____Warning : 1 2 3 4 5 6 7 < 10^{-12} Warning only 6 components could thus be extracted
____Predicting X without NA neither in X nor in Y____
****________________________________________________****

**Comment by brbisheng** [comment]
Dear Professor,

Thank you very much for the detailed solution.

I am trying the package on the 'Don't overfit II' competition. That could be of great help.

Best regards,

Sheng

**Comment by fbertran** [comment]
Dear Sheng BI,

I hope you will find the package useful and wish you good luck for the contest.
Best regards,
Frédéric.
