### ISSUE TITLE
Confidence interval and point estimates of PLS logistic reg

### ISSUE THREAD

**Issue by DiegoAPacheco** [fbertran/plsRglm#2]
Hi! Thank you for your package.
I'm having problems understanding the results of the bootstrap (y, T). The confidence intervals do not contain the point estimate. What am I missing? Please help.

Here a example:

```r
library(plsRglm)
data(aze_compl)

modplsglm <- plsRglm(y~., data = aze_compl, 3, modele = "pls-glm-logistic")
mod_bootYT <- bootplsglm(modplsglm, R = 5000, verbose = FALSE)
try(boxplots.bootpls(mod_bootYT))
mod_bootYT_ci <- confints.bootpls(mod_bootYT)
```

And a plot. 

```r
library(magrittr)
library(ggplot2)
library(data.table)

mod_bootYT_ci[, 7:8] %>%
  as.data.table(keep.rownames = TRUE) %>%
  {.[
    , c("coef", "midpoint") := list(
      modplsglm$Std.Coeffs[-1],
      (V1 + V2)/2
      )
    ]} %>% 
  ggplot(aes(x = reorder(rn, -coef), ymin = exp(V1), ymax = exp(V2), y = exp(coef))) +
  geom_errorbar()+
  geom_point()+
  geom_point(aes(y = exp(midpoint)), col = "red")+
  geom_hline(yintercept = 1, linetype=2) +
  labs(x = "", y = "Odds Ratio")+
  theme_bw()+
  theme(axis.text.x  = element_text(angle=90, vjust=0.7, hjust = 0.5), legend.position = "none")
```   

Black dots are Std.Coeffs and red dots are CI's midpoints for reference.

**Comment by fbertran** [comment]
Hi!
Thanks for your interest for the package. 

I just checked with the Cornell dataset and classic PLS: there seems to be no such issue for the bootstrap (y, T).

library(plsRglm)
data(Cornell)

modplsr <- plsR(Y~.,data=Cornell,4)
Cornell.bootYT <- bootpls(modplsglm, R = 5000, verbose = FALSE, typeboot="fmodel_np")
try(boxplots.bootpls(Cornell.bootYT))
mod_bootYT_ci <- confints.bootpls(Cornell.bootYT,typeBCa = FALSE)

library(magrittr)
library(ggplot2)
library(data.table)

mod_bootYT_ci[, 5:6] %>%
  as.data.table(keep.rownames = TRUE) %>%
  {.[
    , c("coef", "midpoint") := list(
      modplsr$Std.Coeffs,
      (V1 + V2)/2
    )
    ]} %>% 
  ggplot(aes(x = reorder(rn, -coef), ymin = (V1), ymax = (V2), y = (coef))) +
  geom_errorbar()+
  geom_point()+
  geom_point(aes(y = (midpoint)), col = "red")+
  geom_hline(yintercept = 1, linetype=2) +
  labs(x = "", y = "Odds Ratio")+
  theme_bw()+
  theme(axis.text.x  = element_text(angle=90, vjust=0.7, hjust = 0.5), legend.position = "none")


neither with (y,X) bootstrap

library(plsRglm)
data(Cornell)

modplsr <- plsR(Y~.,data=Cornell,4)
Cornell.bootYX <- bootpls(modplsglm, R = 5000, verbose = FALSE, typeboot = "plsmodel")
try(boxplots.bootpls(Cornell.bootYT))
mod_bootYX_ci <- confints.bootpls(Cornell.bootYX,typeBCa = FALSE)

library(magrittr)
library(ggplot2)
library(data.table)

mod_bootYX_ci[, 5:6] %>%
  as.data.table(keep.rownames = TRUE) %>%
  {.[
    , c("coef", "midpoint") := list(
      modplsr$Std.Coeffs,
      (V1 + V2)/2
    )
    ]} %>% 
  ggplot(aes(x = reorder(rn, -coef), ymin = (V1), ymax = (V2), y = (coef))) +
  geom_errorbar()+
  geom_point()+
  geom_point(aes(y = (midpoint)), col = "red")+
  geom_hline(yintercept = 1, linetype=2) +
  labs(x = "", y = "Odds Ratio")+
  theme_bw()+
  theme(axis.text.x  = element_text(angle=90, vjust=0.7, hjust = 0.5), legend.position = "none")


I will look into it for glm models.

**Comment by fbertran** [comment]
It seems ok for plsR logistic and bootstrap (y,X)

library(plsRglm)
data(aze_compl)
[Rplot.pdf](https://github.com/fbertran/plsRglm/files/3060246/Rplot.pdf)


modplsglm <- plsRglm(y~., data = aze_compl, 3, modele = "pls-glm-logistic")
mod_bootYX <- bootplsglm(modplsglm, R = 5000, verbose = FALSE, typeboot = "plsmodel")
try(boxplots.bootpls(mod_bootYX))
mod_bootYX_ci <- confints.bootpls(mod_bootYX)

library(magrittr)
library(ggplot2)
library(data.table)

mod_bootYX_ci[, 7:8] %>%
  as.data.table(keep.rownames = TRUE) %>%
  {.[
    , c("coef", "midpoint") := list(
      modplsglm$Std.Coeffs,
      (V1 + V2)/2
    )
    ]} %>% 
  ggplot(aes(x = reorder(rn, -coef), ymin = exp(V1), ymax = exp(V2), y = exp(coef))) +
  geom_errorbar()+
  geom_point()+
  geom_point(aes(y = exp(midpoint)), col = "red")+
  geom_hline(yintercept = 1, linetype=2) +
  labs(x = "", y = "Odds Ratio")+
  theme_bw()+
  theme(axis.text.x  = element_text(angle=90, vjust=0.7, hjust = 0.5), legend.position = "none")

I will look into it for (y,T) bootstrap.
